const pages=[...document.querySelectorAll('.page')];const navs=[...document.querySelectorAll('.nav')];function show(id){pages.forEach(p=>p.classList.toggle('active',p.id===id));navs.forEach(n=>n.classList.toggle('active',n.dataset.page===id));scrollTo(0,0)}document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>show(b.dataset.page));
const tabButtons=[...document.querySelectorAll('[data-comms-tab]')];const commsPanels=[...document.querySelectorAll('.comms-panel')];tabButtons.forEach(btn=>btn.onclick=()=>{tabButtons.forEach(t=>t.classList.toggle('active',t===btn));commsPanels.forEach(p=>p.classList.toggle('active-panel',p.id===btn.dataset.commsTab))});
const messages=[['Ava Martinez','Today, 9:42 AM','Asked for early check-in and crib availability.'],['Daniel Reed','Today, 8:15 AM','Reported WiFi password not working at Westbury.'],['Priya Shah','Yesterday, 7:01 PM','Asked whether dogs are allowed on the patio.'],['Chris Nolan','Yesterday, 2:33 PM','Confirmed late checkout and trash instructions.']];
messageList.innerHTML=messages.map(m=>`<div class="message"><b>${m[0]}</b><small>${m[1]}</small><p>${m[2]}</p></div>`).join('');
document.querySelectorAll('.message').forEach((el,i)=>el.onclick=()=>{replyName.textContent=messages[i][0];replySummary.textContent=messages[i][2]});
const leads={newLeads:[['Maya Chen','Facebook groups','Westbury House','$1,240','Wants pet-friendly weekend stay'],['Owen Brooks','HotPads leads','Temple Duplex','$2,100','Needs furnished 21-day rental']],qualifiedLeads:[['Lauren King','Zillow leads','Kenley Cottage','$1,760','Budget and dates confirmed'],['Marcus Bell','Airbnb platform','McKinney Place','$3,400','Family trip, verified profile']],followupLeads:[['Sofia Reyes','Facebook groups','Waco Retreat','$1,180','Needs parking answer today'],['Graham Price','Zillow leads','Westbury House','$2,450','Asked for monthly discount']],bookedLeads:[['Nina Patel','Airbnb platform','McKinney Place','$2,980','Booked and access code pending'],['Trevor Adams','HotPads leads','Temple Duplex','$1,920','Deposit captured']]};
function renderLeads(bucket,id){document.getElementById(id).innerHTML=bucket.map(l=>`<div class="lead-card"><b>${l[0]}</b><span>${l[2]} · ${l[3]}</span><small>${l[4]}</small><em class="source-pill">${l[1]}</em></div>`).join('')}
Object.entries(leads).forEach(([id,bucket])=>renderLeads(bucket,id));
const tickets=[['Leaking kitchen sink','Renter: Daniel Reed','Jun 12','triaging'],['AC not cooling upstairs','Teammate: Luis','Jun 11','in process'],['Broken patio chair','Renter: Priya Shah','Jun 10','ordering parts'],['Deep clean follow-up','Teammate: Mara','Jun 9','opened'],['Door keypad battery','Renter: Eric Long','Jun 8','closed']];
ticketRows.innerHTML=tickets.map(t=>`<tr><td><b>${t[0]}</b></td><td>${t[1]}</td><td>${t[2]}</td><td><span class="status">${t[3]}</span></td></tr>`).join('');
const props=[['Westbury House','$412k','88%','https://www.zillow.com'],['Kenley Cottage','$318k','93%','https://www.zillow.com'],['Temple Duplex','$286k','90%','https://www.zillow.com'],['Waco Retreat','$244k','84%','https://www.zillow.com'],['McKinney Place','$525k','96%','https://www.zillow.com'],['Costilla Cabin','$155k','76%','https://www.zillow.com']];
propertyGrid.innerHTML=props.map(p=>`<div class="property"><div class="property-img">${p[0]}</div><div class="property-body"><h3>${p[0]}</h3><p><b>Current value:</b> ${p[1]}</p><p><b>Avg T90 rented days:</b> ${p[2]}</p><a href="${p[3]}" target="_blank">Open Zillow page</a></div></div>`).join('');
const stayData={upcoming:[['Ava Martinez','Jun 18 to Jun 22','Westbury House','$1,840'],['Ben Park','Jun 20 to Jun 25','Kenley Cottage','$2,120']],current:[['Daniel Reed','Jun 10 to Jun 14','Westbury House','$1,620'],['Priya Shah','Jun 9 to Jun 16','McKinney Place','$2,980'],['Chris Nolan','Jun 7 to Jun 20','Temple Duplex','$3,400']],previous:[['Erin Walsh','Jun 1 to Jun 5','Kenley Cottage','$1,375'],['Miles Carter','May 27 to Jun 2','Waco Retreat','$1,640']]};
function renderStay(bucket,id){document.getElementById(id).innerHTML=bucket.map(s=>`<div class="stay" data-stay="${s.join('|')}"><b>${s[0]}</b><span>${s[1]}</span><br><span>${s[2]} · ${s[3]}</span></div>`).join('')}
renderStay(stayData.upcoming,'upcoming');renderStay(stayData.current,'current');renderStay(stayData.previous,'previous');
document.querySelectorAll('.stay').forEach(el=>el.onclick=()=>{const [name,dates,unit,rev]=el.dataset.stay.split('|');stayDetail.innerHTML=`<b>${name}</b><br>Unit rented: ${unit}<br>Dates: ${dates}<br>Length of stay: calculated from booked dates<br>Revenue: ${rev}<br>Rating: pending or latest guest score<br>Notes: ID verified, cleaning scheduled, access code issued, payment captured.`});
